language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
    - /^mkpr/.*$/
    - /^npm-template-sync/.*$/
addons:
  chrome: stable
env:
  - BROWSER=chrome
jobs:
  include:
    - stage: test
      node_js:
        - -12
        - 12.16.0
      script:
        - npm run test
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: "true"
        script:
          - npx semantic-release
